# Sleep_health_and_lifestyle 데이터 준비

   
## 데이터 불러오기
- pandas를 이용해서 데이터 불러오기

In [11]:
import pandas as pd

sleep_data = pd.read_csv("./Sleep_health_and_lifestyle.csv")
sleep_data.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

- 데이터 칼럼 확인

In [12]:
sleep_data.columns

Index(['Gender', 'Age', 'Occupation', 'Sleep Duration', 'Quality of Sleep',
       'Physical Activity Level', 'Stress Level', 'BMI Category',
       'Blood Pressure', 'Heart Rate', 'Daily Steps', 'Sleep Disorder'],
      dtype='object')

---

## 데이터 전처리
   
- '**Sleep Disorder**' 칼럼에 있는 결측 데이터를 확인해보았다.
    - NaN인 경우가 많았는데, 다음 칼럼 주제에 해당되지 않아서 적혀있지 않은 것 같다.
    - 'healthy'로 변경해주었다.

In [13]:
sleep_data[sleep_data["Sleep Disorder"].isna()]

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
7,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
341,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,NaN
342,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,NaN
343,Female,57,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,NaN
358,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,NaN
359,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,NaN

In [14]:
sleep_data.fillna({"Sleep Disorder":"healthy"}, inplace= True)

sleep_data[sleep_data["Sleep Disorder"].isna()]

Empty DataFrame
Columns: [Gender, Age, Occupation, Sleep Duration, Quality of Sleep, Physical Activity Level, Stress Level, BMI Category, Blood Pressure, Heart Rate, Daily Steps, Sleep Disorder]
Index: []

---

## 데이터 가공
- 이 데이터들 중에서 이번 프로젝트에서는 수치형 데이터인 'Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'Heart Rate', 'Daily Steps' 만 이용한다.
   - 수치형 데이터가 아닌 나머지 칼럼은 제거한다.

In [15]:
sleep_data = sleep_data.drop(['Gender', 'Occupation', 'BMI Category', 'Blood Pressure', 'Sleep Disorder'], axis = 1)

sleep_data.columns

Index(['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
       'Stress Level', 'Heart Rate', 'Daily Steps'],
      dtype='object')



---

## 데이터 저장

- 가공한 데이터를 csv파일로 저장한다.
- 이후 대시보드를 만드는데 활용한다.

In [16]:
from google.colab import files

In [17]:
sleep_data.to_csv("Sleep_health_and_lifestyle_dataset.csv", index=False)

In [18]:
files.download("Sleep_health_and_lifestyle_dataset.csv") # 전처리 완료된 파일 다운로드

# 모델 학습

In [20]:
sleep_data["Poor Sleep"] = (sleep_data["Quality of Sleep"] < 7).astype(int) # 7을 기준으로 수면의 질을 이진분류 해준다.

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = sleep_data.drop(["Quality of Sleep", "Poor Sleep"], axis=1)
y = sleep_data["Poor Sleep"]

model = LogisticRegression()
model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [22]:
import joblib

joblib.dump(model, "sleep_quality_model.pkl")

['sleep_quality_model.pkl']